repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: trailing-whitespace
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.73.0
    hooks:
        - id: terraform_fmt
        #- id: terraform_validate
          # Due to a known issue in terraform with configuration_aliases we cannot use terraform_validate right now.
          # The workaround with exclude described in https://github.com/antonbabenko/pre-commit-terraform#terraform_validate
          # didn't work and the error still persisted, so excluding it.
          # We need to wait for an upstream fix in https://github.com/hashicorp/terraform/issues/28490
        - id: terraform_docs
          args:
            - --args=--config=.terraform-docs.yml
